spring:
  application:
    name: netflix-eureka-naming-server

#it is default port for naming-server
server:
  port: 8761

#do NOT register itself
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
