spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AsetK/config-server-2.git
server:
  port: 8888

#http://localhost:8888/limits-service/default - to show retrieved configs
